name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build  

      # Add these two debug steps right after "npm run build"
      - name: Show build output
        run: |
          echo "pwd:" && pwd
          echo "package.json build script:" && cat package.json | jq -r '.scripts.build'
          echo "vite config (if present):" && (ls -1 vite.config.* || true)
          echo "Tree dist/build/out:" && (ls -lah || true) && (ls -lah dist || true) && (ls -lah build || true) && (ls -lah out || true)
          echo "Top of index.html if exists:" && (head -n 5 dist/index.html || head -n 5 build/index.html || head -n 5 out/index.html || true)

      # Make sure the artifact path matches the real build folder:
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist    # change to build or out if the debug step shows otherwise

      - name: Copy index.html to 404.html for SPA routing
        run: cp dist/index.html dist/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

      - name: Show build output
        run: |
          echo "Build script:" && cat package.json | jq -r '.scripts.build'
          echo "dist contents:" && ls -lah dist || true
          echo "Top of index.html:" && head -n 5 dist/index.html || true
